### ISSUE TITLE
Alpine does not keep the installed packages after a new start

### ISSUE THREAD

**Issue by pr-ju** [lima-vm/alpine-lima#101]
Hi, 

Sadly,  Alpine does not keep the installed packages after a new start. Ist this an intended behavior? Files and dirs  in the linux home dir survive, though. 

Done with the regular alpine.yaml template on Macbook Pro M1 with macOS 12.

Best

PR

**Comment by jandubois** [comment]
Yes, that is expected because Alpine boots from an ISO.

You should install any additional packages you need in a provisioning script. In Lima 0.15.1 and later the package cache will be stored on the persistent volume, so on subsequent restarts it will simply reinstall the packages and not download them again.
